set -x

ray job submit --address="http://127.0.0.1:8265" \
   --runtime-env-json='{"working_dir": "/weka/home/tli104/OpenRLHF/openrlhf"}' \
   -- python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 1 \
   --reward_num_nodes 1 \
   --reward_num_gpus_per_node 1 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 4 \
   --vllm_num_engines 2 \
   --vllm_tensor_parallel_size 1 \
   --pretrain meta-llama/Meta-Llama-3.1-8B-Instruct \
   --reward_pretrain Skywork/Skywork-Reward-Llama-3.1-8B-v0.2 \
   --save_path ${SCRATCH_DIR}/scaling_law_ckpts/llama3-8b-rlhf-uf \
   --micro_train_batch_size 1 \
   --train_batch_size 256 \
   --micro_rollout_batch_size 1 \
   --rollout_batch_size 1024 \
   --n_samples_per_prompt 1 \
   --max_epochs 1 \
   --prompt_max_len 1024 \
   --max_samples 100000 \
   --generate_max_len 1024 \
   --advantage_estimator reinforce \
   --zero_stage 3 \
   --bf16 \
   --actor_learning_rate 5e-7 \
   --critic_learning_rate 9e-6 \
   --init_kl_coef 0.01 \
   --prompt_data HuggingFaceH4/ultrafeedback_binarized \
   --input_key prompt \
   --apply_chat_template \
   --normalize_reward \
   --adam_offload \
   --gradient_checkpointing \
   --packing_samples \
   --save_steps -1 \
   --ckpt_path ${SCRATCH_DIR}/scaling_law_ckpts/llama3-8b-rlhf-uf
